### ISSUE TITLE
Hayırlı olsuna geldik

### ISSUE THREAD

**Issue by th3gundy** [fazilaltinel/fazilaltinel.github.io#1]
# Reüzz
`
Yav bu commitler nedir böyle :))
`

**Comment by fazilaltinel** [comment]
Buralar hep bos kalmis aga. Doldurayim dedim

**Comment by th3gundy** [comment]
öyle düz html ile olmaz ki, şekil yapman lazım.
Benim ki Jekyll teması. Tavsiye ederim.

**Comment by fazilaltinel** [comment]
Aga tema, cart-curt bir muhabbet oldugunda aklima hemen su web sayfasi geliyor: [http://kodumunwebsitesi.net/](http://kodumunwebsitesi.net/)

Sonra hemen vazgeciyorum zaten.

**Comment by th3gundy** [comment]
o zaman gg wp.
